/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/Vegetacion.glb 
*/

import React, { useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'

const Vegetacion = (props) => {
  const { nodes, materials } = useGLTF('./models/Vegetacion.glb')


  // Fix tonos y espacio de color
  useEffect(() => {
    Object.values(materials).forEach((mat) => {
      if (!mat) return

      // 1. Evitar tone mapping
      mat.toneMapped = false

      // 2. Forzar sRGB
      mat.colorSpace = THREE.SRGBColorSpace

      // 3. Si tiene texturas, corregirlas una por una
      if (mat.map) mat.map.colorSpace = THREE.SRGBColorSpace
      if (mat.emissiveMap) mat.emissiveMap.colorSpace = THREE.SRGBColorSpace
      if (mat.roughnessMap) mat.roughnessMap.colorSpace = THREE.SRGBColorSpace
      if (mat.normalMap) mat.normalMap.colorSpace = THREE.SRGBColorSpace
      if (mat.metalnessMap) mat.metalnessMap.colorSpace = THREE.SRGBColorSpace
      if (mat.aoMap) mat.aoMap.colorSpace = THREE.SRGBColorSpace

      mat.needsUpdate = true
    })
  }, [materials])


  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Palmera11Web.geometry} material={materials['Material_0.003']} position={[148.424, 26.024, 32.796]} scale={3.673} />
      <mesh geometry={nodes.Palmera02Web.geometry} material={materials['Material_0.014']} position={[108.002, 20.371, 73.35]} rotation={[-Math.PI, 0.535, -Math.PI]} scale={4.186} />
      <mesh geometry={nodes.Arbol02Web.geometry} material={materials['Material_0.001']} position={[-54.833, 22.396, 30.87]} rotation={[Math.PI, -0.61, Math.PI]} scale={2.567} />
      <mesh geometry={nodes.Cactus01Web.geometry} material={materials['Material_0.005']} position={[-67.014, 22.815, 72.04]} rotation={[0, -0.914, 0]} scale={1.902} />
      <mesh geometry={nodes.Arbol06Web.geometry} material={materials['Material_0.009']} position={[0.938, 33.98, -20.163]} rotation={[0, -1.408, 0]} scale={3.762} />
      <mesh geometry={nodes.Palmera04Web.geometry} material={materials['Material_0.016']} position={[-136.973, 25.119, 76.401]} rotation={[Math.PI, -1.3, Math.PI]} scale={4.931} />
      <mesh geometry={nodes.Palmera05Web.geometry} material={materials['Material_0.018']} position={[156.269, 20.125, 72.897]} rotation={[0, 1.004, 0]} scale={3.512} />
      <mesh geometry={nodes.Arbustos01Web.geometry} material={materials.Material_0} position={[-69.011, 22.631, 75.177]} rotation={[0, -0.582, 0]} scale={1.829} />
    </group>
  )
}

useGLTF.preload('./models/Vegetacion.glb')

export default Vegetacion
