/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/Amenities.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

const Amenities = (props) => {
  const { nodes, materials } = useGLTF('./models/Amenities.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.AM_Floor.geometry} material={materials.Concrete} />
      <mesh geometry={nodes.AM_Landscape.geometry} material={materials.Landscape} />
      <mesh geometry={nodes.AM_Cancel.geometry} material={materials.Wood} />
      <mesh geometry={nodes.AM_Walls.geometry} material={materials.Stone} />
      <mesh geometry={nodes.AM_Pergolas.geometry} material={materials.Wood} />
    </group>
  )
}

useGLTF.preload('./models/Amenities.glb')

export default Amenities
