/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/Basamento.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

const Basamento = (props) => {
  const { nodes, materials } = useGLTF('./models/Basamento.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.BA_Basamento.geometry} material={materials.Stone} />
    </group>
  )
}

useGLTF.preload('./models/Basamento.glb')

export default Basamento
