/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/Casona02.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

const Casona02 = (props) => {
  const { nodes, materials } = useGLTF('./models/Casona02.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.C02_Roof.geometry} material={materials.Concrete} />
      <mesh geometry={nodes.C02_Floor03.geometry} material={materials.Concrete} />
      <mesh geometry={nodes.C02_Floor01.geometry} material={materials.Concrete} />
      <mesh geometry={nodes.C02_Floor02.geometry} material={materials.Concrete} />
      <mesh geometry={nodes.C02_Cancel.geometry} material={materials.Wood} />
      <mesh geometry={nodes.C02_Wall.geometry} material={materials.Wall} />
      <mesh geometry={nodes.C02_Cornisa.geometry} material={materials.Wall} />
      <mesh geometry={nodes.C02_Pergola.geometry} material={materials.Wood} />
    </group>
  )
}

useGLTF.preload('./models/Casona02.glb')

export default Casona02
