/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/Casona04.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

const Casona04 = (props) => {
  const { nodes, materials } = useGLTF('./models/Casona04.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.C04_Floor01.geometry} material={materials.Concrete} />
      <mesh geometry={nodes.C04_Floor02.geometry} material={materials.Concrete} />
      <mesh geometry={nodes.C04_Floor03.geometry} material={materials.Concrete} />
      <mesh geometry={nodes.C04_Cancel.geometry} material={materials.Wood} />
      <mesh geometry={nodes.C04_Cornisa.geometry} material={materials.Stone} />
      <mesh geometry={nodes.C04_Roof.geometry} material={materials.Concrete} />
      <mesh geometry={nodes.C04_Wall.geometry} material={materials.Wall} />
      <mesh geometry={nodes.C04_Pergola.geometry} material={materials.Wood} />
    </group>
  )
}

useGLTF.preload('./models/Casona04.glb')

export default Casona04
