/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/Casona03.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

const Casona03 = (props) => {
  const { nodes, materials } = useGLTF('./models/Casona03.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.C03_Floor01.geometry} material={materials.Concrete} />
      <mesh geometry={nodes.C03_Floor02.geometry} material={materials.Concrete} />
      <mesh geometry={nodes.C03_Cancel.geometry} material={materials.Wood} />
      <mesh geometry={nodes.C03_Cornisa.geometry} material={materials.Stone} />
      <mesh geometry={nodes.C03_Roof.geometry} material={materials.Concrete} />
      <mesh geometry={nodes.C03_Wall04.geometry} material={materials.Wall} />
      <mesh geometry={nodes.C03_Wall03.geometry} material={materials.Wall} />
      <mesh geometry={nodes.C03_Wall01.geometry} material={materials.Wall} />
      <mesh geometry={nodes.C03_Wall02.geometry} material={materials.Wall} />
      <mesh geometry={nodes.C03_Pergolas.geometry} material={materials.Wood} />
    </group>
  )
}

useGLTF.preload('./models/Casona03.glb')

export default Casona03
