/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/Casona01.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

const Casona01 = (props) => {
  const { nodes, materials } = useGLTF('./models/Casona01.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.C01_Roof.geometry} material={materials.Concrete} />
      <mesh geometry={nodes.C01_Floor03.geometry} material={materials.Concrete} />
      <mesh geometry={nodes.C01_Floor01.geometry} material={materials.Concrete} />
      <mesh geometry={nodes.C01_Floor02.geometry} material={materials.Concrete} />
      <mesh geometry={nodes.C01_Cancel.geometry} material={materials.Wood} />
      <mesh geometry={nodes.C01_Wall01.geometry} material={materials.Wall} />
      <mesh geometry={nodes.C01_Cornisa.geometry} material={materials.Wall} />
      <mesh geometry={nodes.C01_Pergolas.geometry} material={materials.Wood} />
    </group>
  )
}

useGLTF.preload('./models/Casona01.glb')

export default Casona01
