/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/Casona04.glb 
*/

import React, { useMemo } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import * as   THREE from 'three'


const Casona04 = (props) => {
  const { nodes, materials } = useGLTF('./models/Casona04.glb')


  // Creamos el material solo una vez
  const whiteTransparentMat = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      // color: '#EEE9B2',
      color: '#ffffff',
      transparent: true,
      opacity: 0.8,
      // depthWrite: false,
    })
  }, [])



//   const c04TextureFloor01 = useTexture('./textures/C04/C04_Floor01.jpg')
//   c04TextureFloor01.flipY = false

//   const c04TextureFloor02 = useTexture('./textures/C04/C04_Floor02.jpg')
//   c04TextureFloor02.flipY = false

//   const c04TextureFrames = useTexture('./textures/C04/C04_Frames.jpg')
//   c04TextureFrames.flipY = false

//   const c04TextureWall02 = useTexture('./textures/C04/C04_Wall02.jpg')
//   c04TextureWall02.flipY = false

//   const c04TextureRoof = useTexture('./textures/C04/C04_Roof.jpg')
//   c04TextureRoof.flipY = false

//   const c04TextureWall = useTexture('./textures/C04/C04_Wall.jpg')
//   c04TextureWall.flipY = false

//   const c04TextureWood = useTexture('./textures/C04/C04_Wood.jpg')
//   c04TextureWood.flipY = false

// const meshOpacity = 1.0

// // Floor 01
// const matFloor01 = useMemo(() => {
//   return new THREE.MeshStandardMaterial({
//     map: c04TextureFloor01,
//     transparent: true,
//     opacity: meshOpacity,
//     depthWrite: false,
//   })
// }, [c04TextureFloor01])

// // Floor 02
// const matFloor02 = useMemo(() => {
//   return new THREE.MeshStandardMaterial({
//     map: c04TextureFloor02,
//     transparent: true,
//     opacity: meshOpacity,
//     depthWrite: false,
//   })
// }, [c04TextureFloor02])

// // Frames
// const matFrames = useMemo(() => {
//   return new THREE.MeshStandardMaterial({
//     map: c04TextureFrames,
//     transparent: true,
//     opacity: meshOpacity,
//     depthWrite: false,
//   })
// }, [c04TextureFrames])

// // Wall02
// const matWall02 = useMemo(() => {
//   return new THREE.MeshStandardMaterial({
//     map: c04TextureWall02,
//     transparent: true,
//     opacity: meshOpacity,
//     depthWrite: false,
//   })
// }, [c04TextureWall02])

// // Roof
// const matRoof = useMemo(() => {
//   return new THREE.MeshStandardMaterial({
//     map: c04TextureRoof,
//     transparent: true,
//     opacity: meshOpacity,
//     depthWrite: false,
//   })
// }, [c04TextureRoof])

// // Wall
// const matWall = useMemo(() => {
//   return new THREE.MeshStandardMaterial({
//     map: c04TextureWall,
//     transparent: true,
//     opacity: meshOpacity,
//     depthWrite: false,
//   })
// }, [c04TextureWall])

// // Wood
// const matWood = useMemo(() => {
//   return new THREE.MeshStandardMaterial({
//     map: c04TextureWood,
//     transparent: true,
//     opacity: meshOpacity,
//     depthWrite: false,
//   })
// }, [c04TextureWood])





  return (
    <group {...props} dispose={null}>
      <mesh 
        geometry={nodes.C04W_Floor01.geometry} 
        // material={materials.Concrete} 
        material={ whiteTransparentMat }
      >
        {/* <meshBasicMaterial map={ c04TextureFloor01 } /> */}

        <lineSegments scale={1.001}>
          <edgesGeometry args={[nodes.C04W_Floor01.geometry, Math.PI]} />
          <lineBasicMaterial 
            color="#9B9B9B" 
            transparent 
            opacity={0.9} 
          />
        </lineSegments> 

      </mesh>

      <mesh 
        geometry={nodes.C04W_Floor02.geometry} 
        // material={materials.Concrete} 
        material={ whiteTransparentMat }
      >
        {/* <meshBasicMaterial map={ c04TextureFloor02 } /> */}

        <lineSegments scale={1.001}>
          <edgesGeometry args={[nodes.C04W_Floor02.geometry, Math.PI]} />
          <lineBasicMaterial 
            color="#9B9B9B" 
            transparent 
            opacity={0.9} 
          />
        </lineSegments> 

      </mesh>

      <mesh 
        geometry={nodes.C04W_Frames.geometry} 
        // material={materials.Wood} 
        material={ whiteTransparentMat }
      >
        {/* <meshBasicMaterial map={ c04TextureFrames } /> */}
      </mesh>

      <mesh 
        geometry={nodes.C04W_Wall02.geometry} 
        // material={materials.Wood} 
        material={ whiteTransparentMat }
      >
        {/* <meshBasicMaterial map={ c04TextureWall02 } /> */}

        <lineSegments scale={1.001}>
          <edgesGeometry args={[nodes.C04W_Wall02.geometry, Math.PI]} />
          <lineBasicMaterial 
            color="#9B9B9B" 
            transparent 
            opacity={0.9} 
          />
        </lineSegments> 
      </mesh>

      <mesh 
        geometry={nodes.C04W_Roof.geometry} 
        // material={materials.Wall} 
        material={ whiteTransparentMat }
      >
        {/* <meshBasicMaterial map={ c04TextureRoof } /> */}

        <lineSegments scale={1.001}>
          <edgesGeometry args={[nodes.C04W_Roof.geometry, Math.PI * 2]} />
          <lineBasicMaterial 
            color="#9B9B9B" 
            transparent 
            opacity={0.9} 
          />
        </lineSegments> 

      </mesh>

      <mesh 
        geometry={nodes.C04W_Wall.geometry} 
        // material={materials.Wall} 
        material={ whiteTransparentMat }
      >
        {/* <meshBasicMaterial map={ c04TextureWall } /> */}

        <lineSegments scale={1.001}>
          <edgesGeometry args={[nodes.C04W_Wall.geometry, Math.PI]} />
          <lineBasicMaterial 
            color="#9B9B9B" 
            transparent 
            opacity={0.9} 
          />
        </lineSegments> 

      </mesh>

      <mesh 
        geometry={nodes.C04W_Wood.geometry} 
        // material={materials.Wood} 
        material={ whiteTransparentMat }
      >
        {/* <meshBasicMaterial map={ c04TextureWood } /> */}
      </mesh>

    </group>
  )
}

useGLTF.preload('./models/Casona04.glb')

export default Casona04
