/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/Residencial01.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

const Residencial01 = (props) => {
  const { nodes, materials } = useGLTF('./models/Residencial01.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.R01_Frames.geometry} material={materials.Wood} />
      <mesh geometry={nodes.R01_Teja.geometry} material={materials.Teja} />
      <mesh geometry={nodes.R01_Floorplates.geometry} material={materials.Concrete} />
      <mesh geometry={nodes.R01_Fachada.geometry} material={materials.Wood} />
      <mesh geometry={nodes.R01_Wall01.geometry} material={materials.Wall} />
      <mesh geometry={nodes.R01_Wall02.geometry} material={materials.Wall} />
      <mesh geometry={nodes.R01_Cornisa.geometry} material={materials.Stone} />
      <mesh geometry={nodes.R01_Celosia.geometry} material={materials.Wood} />
    </group>
  )
}

useGLTF.preload('./models/Residencial01.glb')

export default Residencial01
