/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/Residencial02.glb 
*/

import React, { useMemo } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import * as THREE from 'three'

const Residencial02 = (props) => {
  const { nodes, materials } = useGLTF('./models/Residencial02.glb')

  // Creamos el material solo una vez
  const whiteTransparentMat = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      // color: '#EEE9B2',
      color: '#ffffff',
      transparent: true,
      opacity: 0.8,
      // depthWrite: false,
    })
  }, [])


  // const r02TextureFloorplates = useTexture('./textures/R02/R02_Floorplates.jpg')
  // r02TextureFloorplates.flipY = false

  // const r02TextureFrames = useTexture('./textures/R02/R02_Frames.jpg')
  // r02TextureFrames.flipY = false

  // const r02TextureWall = useTexture('./textures/R02/R02_Wall.jpg')
  // r02TextureWall.flipY = false

  // const r02TextureWall02 = useTexture('./textures/R02/R02_Wall02.jpg')
  // r02TextureWall02.flipY = false

  // const r02TextureWood = useTexture('./textures/R02/R02_Wood.jpg')
  // r02TextureWood.flipY = false



  // //Opacity
  // const meshOpacity = 1.0



  // // Floor 01
  // const matFloorplates = useMemo(() => {
  //   return new THREE.MeshStandardMaterial({
  //     map: r02TextureFloorplates,
  //     transparent: true,
  //     opacity: meshOpacity,
  //     depthWrite: false,
  //   })
  // }, [r02TextureFloorplates])


  // // Floor 01
  // const matFrames = useMemo(() => {
  //   return new THREE.MeshStandardMaterial({
  //     map: r02TextureFrames,
  //     transparent: true,
  //     opacity: meshOpacity,
  //     depthWrite: false,
  //   })
  // }, [r02TextureFrames])

  // // Floor 01
  // const matWall = useMemo(() => {
  //   return new THREE.MeshStandardMaterial({
  //     map: r02TextureWall,
  //     transparent: true,
  //     opacity: meshOpacity,
  //     depthWrite: false,
  //   })
  // }, [r02TextureWall])

  // // Floor 01
  // const matWall02 = useMemo(() => {
  //   return new THREE.MeshStandardMaterial({
  //     map: r02TextureWall02,
  //     transparent: true,
  //     opacity: meshOpacity,
  //     depthWrite: false,
  //   })
  // }, [r02TextureWall02])

  // // Floor 01
  // const matWood = useMemo(() => {
  //   return new THREE.MeshStandardMaterial({
  //     map: r02TextureWood,
  //     transparent: true,
  //     opacity: meshOpacity,
  //     depthWrite: false,
  //   })
  // }, [r02TextureWood])



  return (
    <group {...props} dispose={null}>
      <mesh 
        geometry={nodes.R02W_Floorplates.geometry} 
        // material={materials.Concrete}
        material={ whiteTransparentMat }
      >
        <lineSegments scale={1.001}>
          <edgesGeometry args={[nodes.R02W_Floorplates.geometry, Math.PI]} />
          <lineBasicMaterial 
            color="#9B9B9B" 
            transparent 
            opacity={0.9} 
          />
        </lineSegments> 
      </mesh>

      <mesh 
        geometry={nodes.R02W_Frames.geometry} 
        // material={materials.Wood}
        material={ whiteTransparentMat }
      />
      <mesh 
        geometry={nodes.R02W_Wall.geometry} 
        // material={materials.Wall}
        material={ whiteTransparentMat }
      >
        <lineSegments scale={1.001}>
          <edgesGeometry args={[nodes.R02W_Wall.geometry, Math.PI]} />
          <lineBasicMaterial 
            color="#9B9B9B" 
            transparent 
            opacity={0.9} 
          />
        </lineSegments> 
      </mesh>

      <mesh 
        geometry={nodes.R02W_Wall02.geometry} 
        // material={materials.Wood}
        material={ whiteTransparentMat }
      />
      <mesh 
        geometry={nodes.R02W_Wood.geometry} 
        // material={materials.Wood}
        material={ whiteTransparentMat }
      >
        <lineSegments scale={1.001}>
          <edgesGeometry args={[nodes.R02W_Wood.geometry, Math.PI]} />
          <lineBasicMaterial 
            // color="#4B4B4B"
            color="#9B9B9B" 
            transparent 
            opacity={0.9} 
          />
        </lineSegments> 
      </mesh>

    </group>
  )
}

useGLTF.preload('./models/Residencial02.glb')

export default Residencial02
