/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/Residencial02.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

const Residencial02 = (props) => {
  const { nodes, materials } = useGLTF('./models/Residencial02.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.R02_Floorplates.geometry} material={materials.Concrete} />
      <mesh geometry={nodes.R02_Cancel.geometry} material={materials.Wood} />
      <mesh geometry={nodes.R02_Teja.geometry} material={materials.Teja} />
      <mesh geometry={nodes.R02_Wall.geometry} material={materials.Wall} />
      <mesh geometry={nodes.R02_Cornisa.geometry} material={materials.Stone} />
      <mesh geometry={nodes.R02_Fachada.geometry} material={materials.Wood} />
      <mesh geometry={nodes.R02_Celosia.geometry} material={materials.Wood} />
    </group>
  )
}

useGLTF.preload('./models/Residencial02.glb')

export default Residencial02
