/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/Residencial03.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

const Residencial03 = (props) => {
  const { nodes, materials } = useGLTF('./models/Residencial03.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.R03_Cancel.geometry} material={materials.Wood} />
      <mesh geometry={nodes.R03_Floorplates.geometry} material={materials.Concrete} />
      <mesh geometry={nodes.R03_Teja.geometry} material={materials.Teja} />
      <mesh geometry={nodes.R03_Wall.geometry} material={materials.Wall} />
      <mesh geometry={nodes.R03_Wall02.geometry} material={materials.Wall} />
      <mesh geometry={nodes.R03_Cornisa.geometry} material={materials.Stone} />
      <mesh geometry={nodes.R03_Fachada.geometry} material={materials.Wood} />
    </group>
  )
}

useGLTF.preload('./models/Residencial03.glb')

export default Residencial03
