/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/Terrain.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

const Terrain = (props) => {
  const { nodes, materials } = useGLTF('./models/Terrain.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_1.geometry} material={materials.Terreno} />
    </group>
  )
}

useGLTF.preload('./models/Terrain.glb')

export default Terrain
