/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/Terrain_Texture.glb 
*/

import React from 'react'
import { useGLTF, useTexture } from '@react-three/drei'

const TerrainTexture = (props) => {
  const { nodes, materials } = useGLTF('./models/Terrain_Texture.glb')

  const bakedTexture01 = useTexture('./models/TexturaTerrain.jpg')
  bakedTexture01.flipY = false  

  return (
    <group {...props} dispose={null}>
      <mesh 
        geometry={nodes.Object_1.geometry} 
        // material={nodes.Object_1.material}
      >
        <meshBasicMaterial map={ bakedTexture01 } />
      </mesh>
    </group>
  )
}

useGLTF.preload('./models/Terrain_Texture.glb')

export default TerrainTexture
