/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/Texture_Test02.glb 
*/

import React from 'react'
import { useGLTF, useTexture } from '@react-three/drei'

const AmenidadesTexture02 = (props) => {
  const { nodes, materials } = useGLTF('./models/Texture_Test02.glb')

  const bakedTexture01 = useTexture('./models/AM_Floor01_1.jpg')
  bakedTexture01.flipY = false

  const bakedTexture02 = useTexture('./models/AM_Wall01_1.jpg')
  bakedTexture02.flipY = false

  return (
    <group {...props} dispose={null}>
      <mesh 
        geometry={nodes.AM_Floor001.geometry} 
        // material={nodes.AM_Floor001.material} 
      >
        <meshBasicMaterial map={ bakedTexture01 } />
      </mesh>

      <mesh 
        geometry={nodes.AM_Walls001.geometry} 
        // material={nodes.AM_Walls001.material} 
      >
        <meshBasicMaterial map={ bakedTexture02 } />
      </mesh>

    </group>
  )
}

useGLTF.preload('./models/Texture_Test02.glb')

export default AmenidadesTexture02
